# Python for begyndere

## Åbn dokumentet her

1. Gå ind på [https://link.com](https://link.com).
2. Tryk på "Kopíer til Drev"
3. Log ind med din Google-konto

## Integrerede udviklingsmiljøer (IDE'er) til Python: Google Colab og VS Code

Den her fil er en såkaldt Notebook, som kombinerer Python-kode, grafer og formatteret tekst som denne i samme dokument. De 3 trin ovenfor beskriver, hvordan du åbner dokumentet i Google Colab, som er Googles online udviklingsmiljø (IDE) til Python Notebooks. Alternativt kan du også downloade og åbne dokumentet lokalt på din computer - fx i Visual Studio Code (VS Code), som er mit personlige foretrukne IDE til Python.

### Installér Python lokalt (ikke nødvendigt for kurset her)
Hvis du ønsker at åbne Notebook'en i en anden IDE end Colab, så kræver det, at du installerer Python lokalt. 
Som udgangspunkt kan du installere Python gennem [Anaconda-distributionen](https://www.anaconda.com/), som udover Python også installerer en række pakker til databehandling og forskellige IDE'er.

**OBS:** Vær dog opmærksom på, at dit universitet/arbejdsplads muligvis har en anden foretrukken distribution. Se fx DTUs installationsguide [her](https://pythonsupport.dtu.dk/python/install.html). Som udgangspunkt skal du kun installere én distribution, da de ellers kan konflikte med hinanden.

### Tastaturgenveje i Google Colab
| Genvej                | Kommando                          |
|:---------------------:|:---------------------------------:|
| alt (option) + enter  | Kør celle og indsæt ny under      |
| shift + enter         | Kør celle og markér næste         |
| ctr + M, M            | Ændr celle til tekst              |
| ctr + M, Y            | Ændr celle til kode               |
| ctr + D, D            | Fjern celle                       |

## Hello Python!

Python er et programmeringssprog, som muliggør, at du kan instruere computeren i at udføre opgaver for dig. Det gør du ved at give computeren kommandoer.

Fx kan du få Python til at skrive noget tekst med `print` kommandoen:

In [1]:
print('Hello Python!')

Hello Python!


**Bemærk**
1. `print` er navnet på kommandoen. Kommondonavnet efterfølges af paranteser, som man propper indholdet til kommandoen ind i (altså teksten, der skal vises).
2. Teksten, der skal vises er omkranset af citationstegn.

### Kommentarer

Linjer der starter med en havelåge (`#`) er kommentarer, som vil blive ignoreret af Python. Kommentarer er tænkt til at blive læst af mennesker frem for af computeren. I denne notebook holder jeg sproget i kommentarer og i kode generelt på engelsk.

In [2]:
# 1. This line is not executed
# 2. print('This line is also not executed').
print('3. This line is executed')

3. This line is executed


#### Kommentarer på flere linjer

Man kan også lave kommentarer på flere linjer ved at omslutte linjerne med tre enkelt-citationstegn:

In [3]:
'''
These lines are not executed:
print('1.')
print('2.')
print('3.')
'''

print('4. This line is executed')

4. This line is executed


## Python Notebook som en lommeregner

Du kan bruge Python som en lommeregner ved at skrive regnestykkerne ind i kodeceller: 

### Addition, Subtraktion, Multiplikation, Division

In [4]:
2+3

5

In [5]:
2-3

-1

In [6]:
2*3

6

In [7]:
2/3

0.6666666666666666

**OBS: Husk explicit gangetegn mellem paranteser, ellers får du en fejl:**

In [8]:
# # If you remove the commenting (the hash mark, #), the line below will produce an error.
# (2+3)(2-3)

In [9]:
# With an eksplicit multiplication symbol, the calculation works
(2+3)*(2-3)

-5

#### Flere beregninger i samme kodecelle

Du kan lave flere beregninger på samme linje ved at adskille dem med et komma:

In [10]:
2+3, 2-3, 2*3, 2/3

(5, -1, 6, 0.6666666666666666)

Python Notebook'en viser kun resulatet af beregningen fra sidste linje neden for kodecellen:

In [11]:
2+3
2-3
2*3
2/3

0.6666666666666666

Vil du have vist resultatet fra flere linjer, kan du bruge `print`-kommandoen fra tidligere:

In [12]:
print(2+3)
print(2-3)
print(2*3)
print(2/3)

5
-1
6
0.6666666666666666


### Potensopløftning

Hvis du vil udregne $2^3$ kan du bruge en dobbelt asterix (`**`) for at opløfte et tal i en potens:

In [13]:
2**3

8

### Matematiske konstanter og elementære funktioner

For at udregne fx $\sqrt{x}, e^{x}, \ln(x), \sin(x)$ skal vi have fat i et kodebibliotek som NumPy. NumPy-biblioteket er en samling af nyttige funktionalitet til at regne numerisk matematik.

**Hent NumPy-biblioteket ind i sessionen her:**

In [69]:
import numpy as np

Ovenstående er standardmetoden til at hente funktionerne fra NumPy-biblioteket ind i éns kodesession. Det skal læses såddan, at vi loader NumPy-pakken ind under navnet (aliaset) `np`. Fremover kan vi så tilgå NumPy-biblioteket som `np`, så vi ikke hver gang behøver skrive `NumPy`.

**Eksempel: Udregn de følgende fire regnstykker numerisk på samme linje:**

$\sqrt{2} \approx 1.4142, \quad e^2 \approx 7.3891, \quad \ln(e^2) = 2, \quad \sin(-\frac{\pi}{2}) = -1$

In [15]:
np.sqrt(2), np.exp(2), np.log(np.exp(2)), np.sin(-np.pi/2)

(1.4142135623730951, 7.38905609893065, 2.0, -1.0)

### Symbolsk matematik

Python har også SymPy-biblioteket, som i modsætningen til NumPy regner eksakt frem for numerisk. SymPy kan evaluere og simplificere matematiske udtryk eksakt, løse ligninger, tegne funktioner, differentiere, integerere og meget mere.

Som et lille eksempel ville SymPy, i modsætning til NumPy ovenfor, ikke give en decimaltalstilnærmelsen af kvadratroden af 2, men holde fast i den eksakte værdi:

In [16]:
import sympy as sp

sp.sqrt(2)

sqrt(2)

Du kan læse mere om SymPy på deres webside: [https://sympy.org/](https://sympy.org/).

## Introduktion til variable

En variabel er en pladsholder, hvori du kan gemme en værdi - fx tal, tekst eller andet. Du giver pladsholderen et navn, så du nemt kan bruge værdien senere i dit program.

Fx. kan du definere dit navn og vise det.

In [17]:
name = 'Slim Shady'
print(name)

Slim Shady


Eller vi kan definere en talvariabel og udføre beregninger med den

In [18]:
x = 2
y = 3
x*y

6

### Definér variable i den rigtige rækkefølge

Python læser koden i en kodecelle oppefra og ned. Derfor, skal variablene være defineret før, du bruger dem. Fx virker flg. kodecelle ikke:

In [19]:
x = 2
y = 3
print(x*y*z)
z = 3

NameError: name 'z' is not defined

#### Variable gemmes i resten af sessionen

Når du har defineret en variabel i en kodecelle, som du tidligere har kørt, så vil den fortsat være tilgængelig i resten af sessionen:

In [20]:
print(x*y)
print(name)

6
Slim Shady


#### Genstart Sessionen

Du kan genstarte sessionen og derved slette alle variable. I Google Colab gøres dette ved at vælge: "Kørselstid > Genstart Sessionen".

## Datatyper: Tal, tekst, lister, dictionaries, boolske værdier

En variabels type angiver hvilke slags værdier, variablen kan indholde. Python bestemmer automatisk datatyper for variable, men når man programmerer, er det ofte vigtigt selv at vide hvad datatyperne af ens variable er.

### Tal

#### `int`: Heltal (eng. integers)

Heltal, altså $\cdots, -2, -1, 0, 1, 2, \cdots$ har typen `int`. Fx er $a, b, c$ alle af typen `int` nedenfor:

In [21]:
a = 2
b = 3
c = a-b
a, b, c

(2, 3, -1)

Man kan tjekke typen af en variabel med `type`-kommandoen:

In [22]:
type(c)

int

#### `float`: Decimaltal (eng. floating point numbers)

Decimaltalstilnærmelsen til reelle tal har typen `float`.

In [23]:
d = 2/3
d, type(d)

(0.6666666666666666, float)

#### `complex`: Komplekse tal (eng. complex numbers)

Komplekse tal kan repræsenteres på kvadratisk form, hvor `j` bruges til det imaginære tal som er defineret ved $j^2 = -1$.Fx: 

In [24]:
z = 2 + 3j

Hvis du ikke kender til komplekse tal, kan du bare ignorere dette eksempel 😊.

### Tekst

#### `str`: Tekststreng (eng. string)

Et tekststykke har typen `str` og omsluttes af citationstegn i Python:

In [25]:
author = 'Charles Dickens'
print(author)

Charles Dickens


**Dobbelt- og enkeltcitationstegn**

Både dobbelt- og enkeltcitationstegn virker i Python. Den ene mulighed kan bruges, hvis man fx vil indsætte det andet citationstegn som en del af selve teksstrengen. Alternativt kan man bruge `\` til at få citationstegn ind i selve tekststrengen:

In [26]:
print("This 'text string' contains single quotation marks and is therefore encapsulated with double quotation marks, i.e. \" .. \"")

This 'text string' contains single quotation marks and is therefore encapsulated with double quotation marks, i.e. " .. "


#### Sammensætning af teksstykker

Man kan sammensætte flere tekststrenge til én tekststreng ved at "plusse" dem sammen. Fx:

In [27]:
book = 'A Tale of Two Cities'
txt = author + ' is the author of ' + book
print(txt)

Charles Dickens is the author of A Tale of Two Cities


### Lister

#### `list`: Liste (eng. list)

En liste er en ordnet følge af variable.

Fx kan man lave en liste af tal eller en liste med tekststrenge som i eksemplet her, hvor vi definerer en liste af bogtitler og deres tilhørende bedømmelse på Goodreads.

In [28]:
titles = ["A Tale of Two Cities", "The Little Prince", "The Alchemist", "Harry Potter and the Philosopher's Stone", "And Then There Were None"]
ratings = [3.87, 4.32, 3.9, 4.47, 4.28]

##### Tilgå et enkelt element i en liste

Man kan udtrække et enkelt element fra en liste ved at angive dets index. I Python (og mange andre programmeringssprog) er lister 0-indekserede.

Det betyder at det første element har index 0. Derfor kan vi få fat i den første bogtitel ved at skrive:

In [29]:
titles[0]

'A Tale of Two Cities'

Det andet element udtrækkes ved:

In [30]:
titles[1]

'The Little Prince'

Det tredje element udtrækkes ved:

In [31]:
titles[2]

'The Alchemist'

... og så videre

##### Tilgå en følge af elementer

Vi kan også udtrække et interval af elementer. Fx kan vi få bogtitlerne fra og med index 1 og til men ikke med index 4:

In [32]:
titles[1:4]

['The Little Prince',
 'The Alchemist',
 "Harry Potter and the Philosopher's Stone"]

Bemærk at en slice som `1:4` ovenfor altid er **inklusiv** det første index, men **eksklusiv** det sidste index.

### Dictionaries

#### `dict`: Dictionary (eng. dictionary)

En dictionary bruges til at gemme data, hvor hvert element har en `key` (et "opslagsord") og en `value` ("En værdi/definition af opslagsordet"). Fx kan vi gemme data om en bog:

In [33]:
book = {
    "title": "A Tale of Two Cities",
    "year": 1859,
    "author": "Charles Dickens",
    "rating": 3.87
}

##### `keys` og `values`

`book`-variablen har 4 forskellige keys, nemlig `"title"`, `"year"`, `"author"` og `"rating"` og 4 tilhørende værdier.

Vi kan udtrække keys og values sådan her:

In [34]:
book.keys()

dict_keys(['title', 'year', 'author', 'rating'])

In [35]:
book.values()

dict_values(['A Tale of Two Cities', 1859, 'Charles Dickens', 3.87])

##### Udtræk en `value` til en tilhørende `key`

Man kan selvfølgelig udtrække værdien for et bestemt "opslagsord" ved at "slå op i ordbogen". Sådan her:

In [36]:
book['title']

'A Tale of Two Cities'

In [37]:
book['year']

1859

##### Kombinér datatyper

Vi kan selvfølgelig kombinere datatyper. Fx lave dictionaries med lister inden i eller lister med dictionaries i som nedenfor:

In [38]:
books = [
    { "title": "A Tale of Two Cities", "year": 1859, "author": "Charles Dickens", "rating": 3.87 },
    { "title": "The Little Prince", "year": 1943, "author": "Antoine de Saint-Exupéry", "rating": 4.32 },
    { "title": "The Alchemist", "year": 1988, "author": "Paulo Coelho", "rating": 3.9 },
    { "title": "Harry Potter and the Philosopher's Stone", "year": 1997, "author": "J. K. Rowling", "rating": 4.47 },
    { "title": "And Then There Were None", "year": 1939, "author": "Agatha Christie", "rating": 4.28 }
]

Her kan vi fx udtrække titlen for den tredje bog (med index 2) i listen:

In [39]:
books[2]['title']

'The Alchemist'

### Boolske værdier

#### `bool`: Boolsk værdi (eng. boolean)

En `bool` er en variabel, der kun kan antage 2 værdier: `True` (sandt) og `False` (falskt). Man kan definere en boolsk variabel direkete ved simpelthen at skrive:

In [40]:
a = True
b = False
a, b

(True, False)

#### Sammenligning af størrelser

Boolske værdier fremkommer typisk, når vi sammenligner variable. Fx kan vi for $x=1$ spørge, hvorvidt:
1. $x$ er strengt større end $1$? (**falskt**)
2. $x$ er strengt mindre end $1$? (**falskt**)
3. $x$ er lig $1$? (**sandt**)
4. $x$ ikke er lig $1$? (**falskt**)
6. $x$ er større eller lig med $1$? (**sandt**)
7. $x$ er mindre eller lig med $1$? (**sandt**)

I Python gøres dette sådan her:

In [41]:
x = 1

print('1.', x > 1)
print('2.', x < 1)
print('3.', x == 1)
print('4.', x != 1)
print('6.', x >= 1)
print('7.', x <= 1)

1. False
2. False
3. True
4. False
6. True
7. True


Som et andet eksempel, kan man også tjekke, om en tekstreng er lig en anden tekststreng:

In [42]:
name = 'Slim Shady'
print(name == 'Slim Shady')

True


#### Dobbelt- og enkeltlighedstegn
**Bemærk** dobbeltlighedstegnet, `==`, der bruges til den logiske operator, der tjekker, om to værdier er lig hinanden. Enkeltlighedstegn `=` bruges derimod til at definere værdien af en variabel, som vi har set mange eksempler på tidligere.

#### Sammensætning af boolske værdier med logiske operatorer

Man kan sammensætte boolske værdier med de logiske operatorer `and`, `or` og `not` (svarende til de matematiske operatorer $\land, \lor, \lnot$). Fx

In [43]:
x = 1
print(x > 0 and x <= 2)
print(x <= 0 or x > 2)
print(not (x > 0 and x <= 2))

True
False
False


## If ... else statements

Man kan køre kode afhængigt af, om en boolsk værdi er sand eller falsk. Dette gør man, med `if ... else` statements:

In [44]:
x = 1
if x > 0:
    print('x is positive')
else:
    print('x is not positive')

x is positive


I eksemplet ovenfor bliver kodelinjen `print('x is positive')` kun kørt, hvis udsagnet `x > 0` er `True`. Hvis $x$ er negativ eller 0, bliver linjen `print('x is not positive')` derimod kørt. Du kan prøve at ændre værdien af $x$ og se, at det stemmer.

Bemærk det lille kolon efter hver `if` og `else` statement.

### Indrykning

I Python er indrykningen (altså mellemrummet inden kodelinjen) afgørende for, hvilken kode der køres. Se fx. følgende eksempel

In [45]:
x = 1
if x != 1:
    print('line 1')
    print('line 2')
print('line 3')

line 3


Den tredje linje bliver printet, idet den ikke er indrykket og derfor ikke omfattet af `if`-statement'en.

#### Indlejrede if statements

Med indrykning kan man lave flere if statements inde i hinanden. Fx:

In [46]:
x = 1
if x > 0:
    print('x > 0')
    if x <= 2:
        print('0 < x <= 2')
        if x != 2:
            print('0 < x < 2')
        else:
            print('x is exactly 2')

x > 0
0 < x <= 2
0 < x < 2


### Else if

En `elif` statement (forkortelse for "else if") bliver kørt, hvis den boolske værdi er sand og de forudgående tilfælde ikke er opfyldt. Fx:

In [47]:
x = 1

if x > 2:
    print('2 < x')
elif x > 1:
    print('1 < x <= 2')
elif x > 0:
    print('0 < x <= 1')
else:
    print('x <= 0')

0 < x <= 1


## Funktioner

En funktion er en måde at samle noget kodefunktionalitet på i en kodeblok, som man så kan køre igen og igen, uden at skulle skrive kodelinjerne på ny hver gang.

Man kan tænke på en funktion som en maskine, der
1. evt. kan tage nogle inputs.
2. udfører nogle operationer.
3. evt. spytter et output ud igen.

### Funktion uden input og output

Man definerer en funktion i Python ved at skrive:

In [48]:
def print_lines():
    print('Line 1')
    print('Line 2')

Når funktionen er defineret, har vi nu en kommando kaldet `print_lines` til rådighed. I programmeringsterminologi siger man, at man "kalder funktionen", når man bruger kommandoen `print_lines` (eng. "call the function"):

In [49]:
print_lines()
print_lines()
print_lines()

Line 1
Line 2
Line 1
Line 2
Line 1
Line 2


**Bemærk**, at vi faktisk allerede har set eksempler på funktioner som fx kommandoen `print()`. Et sted i Pythons maskinrum findes altså også en definition på funktionen `print`.

#### Indrykning

Indrykningen har også betydning for funktioner. Al "indmad" i en funktion skal være indrykket og vil først blive kørt, når funktionen kaldes. Betragt fx følgende eksempel:

In [53]:
def print_lines():
    print('Line 1')
    print('Line 2')
print('Line 3')
print_lines()

Line 3
Line 1
Line 2


`'Line 3'` bliver vist først og først når vi kalder funktionen `print_lines()` bliver de to kodelinjer med 'Line 1' og 'Line 2' kørt.

### Funktion med input, men uden output

Funktioner kan tage variable som input mellem paranteserne. Værdier, der gives som input til en funktion kaldes "argumenter" (eng. arguments)

In [50]:
def greet(greeting, name):
    print(greeting + ' ' + name)

greet('Hello', 'Slim Shady')

Hello Slim Shady


### Funktion med input og output

Når en funktion har kørt sin indmad, kan man få den til at spytte en værdi tilbage til brugeren, der har kaldt funktionen. Dette kaldes at "returnere" en værdi. Fx:

In [56]:
def sum_numbers(a, b):
    return a + b

sum_of_numbers = sum_numbers(1, 2)
print(sum_of_numbers)

3


## Løkker (eng. loops)

Med løkker kan man få kodelinjer til at gentage sig. Den mest anvendelige type løkke er "for loops", hvis indmad gentages for hvert element i en liste.

Fx kan vi vise alle tekststrenge i en liste:

In [63]:
for name in ['Hans', 'Grethe', 'Anders']:
    print(name)

Hans
Grethe
Anders


**Bemærk** igen at indrykningen er vigtig.

Vi kunne også kvadrere alle tallene i én liste:

In [67]:
for a in [1, 2, 3]:
    print(a**2)

1
4
9


#### Funktioner i løkker

Man kan selvfølgelig også kalde funktioner i en løkke. Fx kan vi lave en funktion til at omregne vinkler i grader om til vinkler i radianer og køre denne funktion på alle vinkler i en liste:

In [68]:
import numpy as np

def deg_to_rad(deg):
    return deg * np.pi/180

angles = [0, 90, 180]

for angle in angles:
    print(deg_to_rad(angle))

0.0
1.5707963267948966
3.141592653589793


Bemærk, at vi for en sikkerheds skyld igen har importeret NumPy-biblioteket, som vi stiftede bekendskab med noget tidligere. Resultatet ovenfor passer med decimaltalstilnærmelsen for $0$, $\pi/2$ og $\pi$ radianer.

## NumPy

NumPy kodebiblioteket har langt mere funktionalitet end blot de elementære matematiske funktioner og konstanter, som vi har set hidtil.

Et centralt element i NumPy-pakken er datatypen `numpy.ndarray` også blot kaldet en Array (dog ikke helt det samme som en Array i andre programmeringssprog).

Forestil dig, at vi har en liste med datapunkter opsamlet i et eksperiment. Fx $x$ og $y$ positioner i meter fra et skrå kast:

In [73]:
x = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
y = [1.03,  1.1 ,  1.14,  1.17,  1.09,  1.  ,  0.87,  0.71,  0.52, 0.29, -0.03]

Hvis vi skal konvertere positionerne til cm i stedet for m, så skal vi bare gange alle tal med 100.

Naivt kunne man måske tænke, at vi bare kan gøre det ved at skrive `x*100`:

In [74]:
x_cm = x*100
print(x_cm)

[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.

**Desværre virker det ikke bare at gange en liste med et tal!**

I stedet for at gange alle tallene i listen med 100, så har Python kopieret listen 100 gange. Vil man godt have den forventede adfærd, hvor $x$ blev skaleret med 100 i stedet for at blive kopieret 100 gange, så skal man i stedet for en `list` bruge en `numpy.ndarray`:

#### `numpy.ndarray`: NumPy Array

Man kan lave en Array med kommandoen `np.array()`, som man skal give en liste som input. Fx kan vi lave en NumPy array ud fra listen `x`:

In [123]:
x_np = np.array(x)
x_np

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

En NumPy array fungerer lidt som en vektor i matematik, så ganger du fx en array med 100, så skaleres hele array'en præcis som vi ønsker det:

In [124]:
x_np * 100

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#### Operationer mellem arrays

Man kan også lave operationer mellem NumPy Arrays. Fx gange to arrays elementvis med hinanden eller trække dem elementvis fra hinanden:

In [125]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
u*v, u-v

(array([ 4, 10, 18]), array([-3, -3, -3]))

#### Matematiske funktioner på arrays

Man kan også udføre matematiske funktioner på samtlige elementer i sin array fx:

In [127]:
np.exp(u)

array([ 2.71828183,  7.3890561 , 20.08553692])

#### Vigtigt: En NumPy Array er ikke en liste!

Det er vigtigt at forstå, at en liste og en NumPy Array ikke er den samme datatype. Ovenstående eksempel på, hvad der sker hvis man ganger med en skalar eller lægger to variable sammen, er et godt eksempel på forskellen mellem de to datatyper.

#### Matricer og ND Arrays

Med NumPy kan man lave meget effektiv numerisk lineær algebra, hvilket er særdeles nyttigt til statistik, databehandling og maskinlæring (AI). Hvis du ikke kender til matrix-regning og lineær algebra, kan du ignorere dette afsnit.

En matrix repræsenteres i NumPy som en 2-dimensionel array og kan laves ved at give en liste med lister indeni til `np.array()` kommandoen:

In [128]:
A = np.array([  [1, 2], 
                [3, 4]])
B = np.array([  [0], 
                [-1]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[ 0],
        [-1]]))

Man kan også lave flerdimensionelle arrays (ND arrays) fx til at repræsentere rgb-pixelværdier i et billede el.lign.

##### Matrixoperationer og Lineær Algebra

**Matrixmultiplikation** udføres med `@`:

In [129]:
A @ B

array([[-2],
       [-4]])

**Transponering** klares med `.T`:

In [130]:
A.T

array([[1, 3],
       [2, 4]])

**Prikprodukt** mellem vektorer kan bestemmes ved at kombinere transponering og matrixmultiplikation:

In [131]:
v = np.array([3, 4])
v.T @ v

25

**Vektorlængde** kan fx bestemmes ved at tage kvadratroden af prikproduktet med vektoren selv:

In [132]:
v_length = np.sqrt(v.T @ v)
v_length

5.0

Alternativt har `NumPy` et dedikeret `linalg` bibliotek til lineær algebra. Fx kan vi bestemme vektorlængden ved:

In [133]:
np.linalg.norm(v)

5.0

#### Egenskaber ved arrays

En array har forskellige egenskaber (eng. properties), som man kan trække ud. De vigtigste er `shape` og `size`, som forklares nedenfor:

In [152]:
A = np.array([  [1, 2, 3], 
                [4, 5, 6]])
u = np.array([1, 2, 3])
A, u

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3]))

##### `.shape`: Formen (ant. rækker, kolonner, etc.) af en array 

In [153]:
A.shape, u.shape

((2, 3), (3,))

##### `.size`: Antal elementer i array

In [151]:
A.size, u.size

(6, 3)

#### Andre metoder til at lave en NumPy Array

Udover `np.array()` har NumPy har en række funktioner til at lave arrays. Fx:

`np.zeros(shape)`

Eksempel: Lav en Array af størrelse $2 \times 3$ med 0-taller allevegne (svarende til en $2 \times 3$ matrix):

In [90]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

`np.ones(shape)`

Eksempel: Lav en Array af størrelse $2 \times 3$ med 1-taller allevegne:

In [91]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

`np.arange(start, stop)`

Eksempel: Lav en 1D Array med tallene fra 1 til og med 6:

In [92]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [139]:
# x = np.linspace(0, 1, 11)
# g = 9.82
# theta = np.pi/4
# y0 = 1
# v0 = 2.2
# eps = 0.05* np.random.rand(x.shape[0])
# y = y0 -g/(2*(np.cos(theta)**2)*(v0**2)) * (x**2) + np.tan(theta) * x + eps


# import matplotlib.pyplot as plt

# plt.plot(x, np.round(y, 2), 'k.')
# plt.grid()
# # plt.xlim(0, 0.5)
# plt.ylim(0, 1.3)

##